version: '3.9'

services:

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ${MINIO_DATA_DOCKER_MOUNT}:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_SERVER_URL: http://minio:9000
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s #CHANGE
      timeout: 10s #CHANGE
      retries: 1   #CHANGE

  minio-client:
    image: minio/mc
    container_name: minio_mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c 
      "
        until mc config host add myminio http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD}; do
          echo 'Waiting for MinIO service to start...'
          sleep 5
        done;
        if ! mc ls myminio/BUCKET_NAME; then
          mc mb myminio/BUCKET_NAME;
        fi
        mc anonymous set public myminio/BUCKET_NAME;
        mc anonymous set download myminio/BUCKET_NAME;
        mc admin user add myminio SERVER_USER SERVER_USER_PASS;
        mc admin policy set myminio readwrite user=SERVER_USER;
      "

volumes:
  minio-data:
    name: ${MINIO_DATA_DOCKER_MOUNT}

networks:
  default:
    attachable: true

